# Generated by Django 4.2.23 on 2025-08-29 05:07

from django.db import migrations, models
import fileservice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=fileservice.models.generate_file_code, max_length=8, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_token', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'file_shares',
                'indexes': [models.Index(fields=['code'], name='file_shares_code_91f0e7_idx'), models.Index(fields=['created_at'], name='file_shares_created_8e8170_idx'), models.Index(fields=['expires_at'], name='file_shares_expires_1bc2a0_idx')],
            },
        ),
    ]
